### ISSUE TITLE
`rich_text` Block is not available when post messages using Web API

### ISSUE THREAD

**Issue by akuzia** [slack-go/slack#1087] opened 2022-07-07 13:23 UTC
### What happened

Simple RichTextBlock [is valid](https://app.slack.com/block-kit-builder/T02F5BV04GL#%7B%22blocks%22:%5B%7B%22type%22:%22rich_text%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22test%20message%22%7D%5D%7D%5D%7D%5D%7D) in block kit, but not valid in api. Returned error has no useful metadata.

### Expected behavior

RichText is successfuly sent, nil error returned

#### reproducible code

```golang
package main

import (
	"fmt"

	"github.com/slack-go/slack"
)

func main() {
	api := slack.New("xoxb-...")
	block := slack.NewRichTextBlock("",
		slack.NewRichTextSection(
			slack.NewRichTextSectionTextElement("test message", nil),
		),
	)
	if _, _, err := api.PostMessage(
		"test",
		slack.MsgOptionBlocks(block),
	); err != nil {
		err := err.(slack.SlackErrorResponse)
		fmt.Printf("slack: %s: %v\n", err.Error(), err.ResponseMetadata)
	}
}

```

### Versions
- Go: `go1.18.3 linux/amd64`
- slack-go/slack: `v0.11.0`

**Comment by kanata2** [comment] 2022-09-11 23:20
I can't reproduce.
Could you give me some more details?

**Comment by akuzia** [comment] 2022-09-12 06:43
I've updated the lib, enabled debugging and still getting the same error with code below:

```golang
package main

import (
	"encoding/json"
	"fmt"

	"github.com/slack-go/slack"
)

func main() {
	api := slack.New(
		"xoxb-...",
		slack.OptionDebug(true),
	)
	block := slack.NewRichTextBlock("",
		slack.NewRichTextSection(
			slack.NewRichTextSectionTextElement("test message", nil),
		),
	)

	if blocksJson, err := json.Marshal(block); err == nil {
		fmt.Println(string(blocksJson))
	} else {
		fmt.Println(err)
	}

	if _, _, err := api.PostMessage(
		"test",
		slack.MsgOptionBlocks(block),
	); err != nil {
		err := err.(slack.SlackErrorResponse)
		fmt.Printf("slack: %s: %v\n", err.Error(), err.ResponseMetadata)
	}
}
```

go mod for reference:
```golang
module github.com/akuzia/first

go 1.18

require github.com/slack-go/slack v0.11.3

require github.com/gorilla/websocket v1.4.2 // indirect
```

Output:
```
# go run ./main.go
{"type":"rich_text","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"test message"}]}]}
slack-go/slack2022/09/12 09:41:17 chat.go:227: Sending request: blocks=%5B%7B%22type%22%3A%22rich_text%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22test+message%22%7D%5D%7D%5D%7D%5D&channel=test&token=xoxb-...
slack: invalid_blocks: { [] []}
```

**Comment by kanata2** [comment] 2022-09-12 09:08
Thanks. I was able to reproduce it.
By the way, it does not seem to be a library's bug because I get an error when I use Tester.
I'll do some more research and report back here if I find anything.

**Comment by kanata2** [comment] 2022-09-13 00:39
@akuzia 
I inquired Slack support about this and got an answer.
These are data structures that can only be used when received as a response from Slack, so we cannot use `rich_text` or `rich_text_section` for user posting messages...

p.s.
You can use webhook if you want `rich_text` block.

**Comment by kanata2** [comment] 2022-09-13 00:44
I'm going to close this issue but I'd like to think of some way not to have problems with this confusing specification.
Thank you for reporting.

**Closed as completed by kanata2** 2022-09-13 00:44 UTC
Labels: spec undocumented
