### ISSUE TITLE
How to send ephemeral messages

### ISSUE THREAD

**Issue by noandrea** [slack-go/slack#191] opened 2017-09-19 10:12 UTC
Hello, 
Is there a way to send [ephemeral messages](https://api.slack.com/methods/chat.postEphemeral) ? I cannot find out how. 

all the best

**Comment by sevagh** [comment] 2018-01-04 20:21
I'm having trouble using the new PostEphemeral() method @luqasn (or anybody else). If I should create a new issue, let me know.

My RTM bot replies with blank messages:

```go
params := slack.PostMessageParameters{
        Text: "This is a test of ephemeral messaging!",
        Channel: ev.Channel,
        User: ev.User,
        AsUser: true,
}

msgOptPMParams := slack.MsgOptionPostMessageParameters(params)

fmt.Printf("%# v\n", pretty.Formatter(params))
_, err := slackClient.PostEphemeral(
        ev.Channel,
        ev.User,
        msgOptPMParams,
)
if err != nil {
        log.Infof("Err when sending ephemeral message: %v", err)
}
```

Debug print output:

```text
slack.PostMessageParameters{
    Text:            "This is a test of ephemeral messaging!",
    Username:        "",
    AsUser:          true,
    Parse:           "",
    ThreadTimestamp: "",
    ReplyBroadcast:  false,
    LinkNames:       0,
    Attachments:     {},
    UnfurlLinks: false,
    UnfurlMedia: false,
    IconURL:     "",
    IconEmoji:   "",
    Markdown:    false,
    EscapeText:  false,
    Channel:     "C<redacted>",
    User:        "U<redacted>",
}
```

Screenshot:

![screenshot from 2018-01-04 12-15-18](https://user-images.githubusercontent.com/8574092/34582558-19bf0936-f149-11e7-8279-56ad0b51384e.png)

Previously, my bot would reply using RTM which worked fine and displayed messages correctly:

```go
sc.rtm.SendMessage(sc.rtm.NewOutgoingMessage("This is a message!"), ev.Channel))
```

**Comment by luqasn** [comment] 2018-01-04 20:50
I also find the current implementation confusing, as it is not "high-level" (give it a text and parameters) but requires you to manually stitch together options. In my opinion, there should be a direct equivalent to the PostMessage() call (and maybe SendMessage, haven't used that before).

```go
func PostEphemeral(rtm *slack.RTM, channel, user, text string, params slack.PostMessageParameters) (string, error) {
	return rtm.PostEphemeral(
		channel,
		user,
		slack.MsgOptionText(text, params.EscapeText),
		slack.MsgOptionAttachments(params.Attachments...),
		slack.MsgOptionPostMessageParameters(params),
	)
}
```
And this is how I use it:
```go
_, err := PostEphemeral(rtm, channel, user, msg, slack.PostMessageParameters{})
```

I think you are simply missing the MsgOptionText(), so your message has no body. It is confusing that it is defined in the parameters, but has no effect, though...
In other places, I use the PostMessageParameters to send an attachment with the ephemeral message.

Does that help?

btw: the PR linked in this ticket is not the one that was merged.

**Comment by sevagh** [comment] 2018-01-04 20:59
Thanks a lot, that worked.

**Comment by luqasn** [comment] 2018-01-04 21:31
No problem! Funny: I have also used this to develop an on-call bot ;)

**Comment by james-lawrence** [comment] 2018-02-02 03:23
@luqasn agreed we could make posting Ephemeral messages cleaner.

I'd happily take a cleaner version for this. maybe with an eye towards cleaning up the top level api but delegating as you did to SendMessage.

SendMessage when I wrote it was intended to be a flexible escape hatch used but higher order functions for common usecases. so this would fall right in line with that approach.

**Comment by james-lawrence** [comment] 2018-02-02 03:24
there is also a PR that removes the text field from the Parameters structure, it just needs a rebase.

**Closed as completed** 2019-08-31 12:33 UTC
Labels: documentation
