### ISSUE TITLE
RTM channels often get rate-limited since upgrade from a 2017 version of the library to latest

### ISSUE THREAD

**Issue by valeriansaliou** [slack-go/slack#613] opened 2019-10-22 17:11 UTC
Hello there,

First of all, thanks a ton for your slack library. We heavily use it at Crisp to run our Slack connector, which lets our user reply to their Crisp messages right from Slack.

Last week, I've updated our Slack plugin from an end-of-2017-ish version of the library, to latest commit from master (1st Sept 2019). We're now seeing reports of RTM channels unable to connect after the service has been running for some time, which we did not experience at all before the update.

The error we see from our logs is the following:

```
Received connection error event from Slack for website: ****, will sleep for 30 seconds before reconnecting [error: slack rate limit exceeded, retry after 58s]
```

In this part of our own code:

```go
for {
      select {
            case msg := <- rtmBinding.IncomingEvents:
                  switch evt := msg.Data.(type) {
                  case *slack.ConnectionErrorEvent:
                    // Process random sleep delay
                    rand.Seed(time.Now().UnixNano())

                    randomDelay := connectionErrorSleepBaseDelay + (connectionErrorSleepRandomDelay * rand.Intn(connectionErrorSleepRandomGap))

                    log.Errorf("Received connection error event from Slack for website: %s, will sleep for %d seconds before reconnecting [error: %s]", websiteID, randomDelay, evt.ErrorObj)

                    // Sleep for a few seconds (retry after a while, this avoids rate limits)
                    time.Sleep(time.Duration(randomDelay) * time.Second)
      }
}
```

Did anything change in the way the RTM connection manager handles its connections? We open 1,000s of parallel RTM sessions from the same IP address, that for different Slack teams with their OAuth tokens. We've not changed anything in the way our code manages those parallel connections, except from bumping to the latest version of your library.

Note that rebooting our system succeeds in recovering all connections. To me it seems as if there was some broken state in the "state machine" for the library connection manager. Note that we use a time.Sleep to prevent reconnecting immediately in case of a connection error, which worked well w/ last version. If you upgraded the connection manager system to a split-goroutine system, that may explain why we're unable to throttle ourselves now w/ time.Sleep.

Just need confirmation of what changed, or if there's any suspected issue in the RTM manager in the library.

Thanks!

**Comment by valeriansaliou** [comment] 2019-10-22 17:14
Oh, as a side note to this issue, we've noticed our Slack plugin consumes significantly less RAM (previously ~900MB, now ~100MB) since the update. I don't know if something changed in the way RTM events are parsed or heap is allocated for parsing purposes, but the improvement is amazing.

**Comment by stephen-gardner** [comment] 2019-11-04 10:38
I'm experiencing some issues with connection rate limiting too, although I haven't used this library until recently.

I've hooked the `ConnectedEvent`, `DisconnectedEvent`, and `ConnectionErrorEvent`; here's the code ranging `rtm.IncomingEvents`:
```
case *slack.ConnectionErrorEvent:
	mom.log.Printf("Connection error (%d attempts): %s; reconnecting in %v...\n", ev.Attempt, ev.Error(), ev.Backoff)

case *slack.ConnectedEvent:
	mom.log.Printf("Connected (#%d)...\n", ev.ConnectionCount+1)

case *slack.DisconnectedEvent:
	mom.log.Printf("Disconnected (Intentional: %v, Reload: %v)...\n", ev.Intentional, mom.reload)
```

And this seems to happen roughly every 8 hours:
```
Iris: 2019/11/03 17:54:47 Connected (#1)...
Iris: 2019/11/04 02:16:42 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:42 Connected (#2)...
Iris: 2019/11/04 02:16:42 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:43 Connected (#3)...
Iris: 2019/11/04 02:16:43 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:43 Connected (#4)...
Iris: 2019/11/04 02:16:43 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:43 Connected (#5)...
Iris: 2019/11/04 02:16:43 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:43 Connected (#6)...
Iris: 2019/11/04 02:16:43 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:44 Connected (#7)...
Iris: 2019/11/04 02:16:44 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:44 Connected (#8)...
Iris: 2019/11/04 02:16:44 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:44 Connected (#9)...
Iris: 2019/11/04 02:16:44 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:44 Connected (#10)...
Iris: 2019/11/04 02:16:44 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:44 Connected (#11)...
Iris: 2019/11/04 02:16:44 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/04 02:16:45 Connection error (1 attempts): slack rate limit exceeded, retry after 58s; reconnecting in 58s...
Iris: 2019/11/04 02:16:45 Connection error (2 attempts): slack rate limit exceeded, retry after 58s; reconnecting in 58s...
Iris: 2019/11/04 02:17:43 Connected (#12)...
```

For some reason, when the connection drops every 8 hours, the connection is rapidly made and immediately disconnected, and doesn't stick until after the rate limiting.

**Comment by valeriansaliou** [comment] 2019-11-04 10:57
Experiencing a similar pattern. All connections get disconnected periodically (likely 10 hours or so), and backend fails to recover connection for a small percentage of those; does not happen on weekends.

My guess is that Slack is doing WS service deployments and breaks active connections periodically, which the latest version of the library has an issue recovering in some cases.

**Comment by valeriansaliou** [comment] 2019-11-05 08:25
Would that be fixed? 900741889b0bd18318f120c8f3059a98302798ee

**Comment by stephen-gardner** [comment] 2019-11-06 05:58
```
MOTHER: 2019/11/05 12:56:18 Connected (#1)...
Iris: 2019/11/05 12:56:18 Connected (#1)...
Percy: 2019/11/05 12:56:18 Connected (#1)...
...
MOTHER: 2019/11/05 20:57:32 Disconnected (Intentional: false, Reload: false)...
MOTHER: 2019/11/05 20:57:32 Disconnected (Intentional: false, Reload: false)...
MOTHER: 2019/11/05 20:57:33 Connected (#2)...
Percy: 2019/11/05 21:10:08 Disconnected (Intentional: false, Reload: false)...
Percy: 2019/11/05 21:10:08 Disconnected (Intentional: false, Reload: false)...
Percy: 2019/11/05 21:10:08 Connected (#2)...
Iris: 2019/11/05 21:13:54 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/05 21:13:54 Disconnected (Intentional: false, Reload: false)...
Iris: 2019/11/05 21:13:55 Connected (#2)...
```

The recent updates seems to have mostly fixed the issue for me. I get duplicated disconnected events when Slack kills the connection (which is a non-issue in my situation), but at least the connection errors and rate limiting has disappeared.

**Comment by dpup** [comment] 2019-11-21 00:47
I had opened #635 with similar issues. I've also been talking to Slack API support about our issue. They've been very helpful. I also think the recent updates have resolved many of the issues. It sounds like there's still a chance there are hung connections hanging around. But I'm not sure how to verify on our side. 

@stephen-gardner & @valeriansaliou : Apparently Slack will close channels after 8 hours. So this is expected if connections are all established simultaneously after a deploy. We're adding a random expiration to make the occurrence less noisy.

**Comment by nolanlum** [comment] 2019-11-21 01:20
I think my issue #604 is the root cause of the issue we're seeing here, which I believe was fixed in latest `master`. I haven't had a chance to verify yet since I'm still running off of my own fork.

**Comment by dpup** [comment] 2019-11-21 03:24
I deployed the new code today, should see after 8 hours how it handles all the goodbyes. Will report back.

**Comment by dpup** [comment] 2019-11-21 20:31
Ok, our bots all had their connections refreshed at at 9pm and 5am and everything looked good. No rate limit exceptions.

**Comment by valeriansaliou** [comment] 2019-11-21 21:39
No more exceptions w/ latest from master for us too.

**Closed as completed** 2021-01-21 15:07 UTC
