### ISSUE TITLE
using api.postMessage doesn't post from authenticated user

### ISSUE THREAD

**Issue by jhebb-lm** [slack-go/slack#142] opened 2017-03-03 13:30 UTC
Using the API with a slackbot, If I send a message using `rtm.SendMessage(rtm.NewOutgoingMessage("Hello World", channel))` it posts from my bot as expected but if I try and use an attachment with `api.PostMessage(channel, "Hello World", params)` it posts from a generic bot user - is there something else I need to do post from my own bot using an attachment?

I followed the example here:
https://github.com/nlopes/slack/blob/master/examples/messages/messages.go

**Comment by Davejkane** [comment] 2017-04-03 13:49
You need to set params.AsUser as true.

params := slack.NewPostMessageParameters
params.AsUser = true
api.PostMessage(channel, "Hello World", params)

**Comment by gemina** [comment] 2017-04-17 16:18
@Davejkane I tried like this also and got the same error, message displayed as "bot"

**Comment by Davejkane** [comment] 2017-04-18 06:45
Is that perhaps because I accidentally left the parenthesis off? should be
    params := slack.NewPostMessageParameters()

**Comment by gemina** [comment] 2017-04-18 06:55
Same, I tried that one also

**Comment by Davejkane** [comment] 2017-04-18 07:27
Is it at all possible to share your code? Obviously not your bot token.

**Comment by dlsniper** [comment] 2017-04-21 22:07
Hi,

I've merged #146 without noticing a regression on the AsUser option.
Luckily @vrischmann was quick to identify it and fix it in #156 so please try this again. I've verified it using https://github.com/gopheracademy/gopher/blob/master/bot/bot.go#L121 which should also serve as an example on how to use this.
Not sure if it solves the initial issue but I think it should as well.
Thank you and I apologize for the issue, testing is something I know I need to improve in the future for this package.

**Comment by gemina** [comment] 2017-04-22 05:56
Thank you

**Comment by james-lawrence** [comment] 2018-02-02 03:16
sounds like this was fixed. closing.

**Closed as completed by james-lawrence** 2018-02-02 03:16 UTC
